{% set version = "6.1.1" %}

package:
  name: mantid-workbench
  version: {{ version }}

source:
  git_url: https://github.com/mantidproject/mantid.git
  git_tag: 32079_mantidqt_separate_package
  patches:
    - bundle.patch  # [osx]
    - install_patch.patch

build:
  number: 0
  skip: true  # [py36 and aarch64]
  entry_points:
    - workbench = workbench.app.main:main
  osx_is_app: true


requirements:
  build:
    - {{ compiler("cxx") }}
    - ninja  # [unix]
    - cmake
  host:
    - boost 1.75.*
    - mantid-qt
    - python.app  # [osx]
    - setuptools 48.0.*
  run:    
    - psutil
    - python.app  # [osx]

test:
  imports:
    - workbench

about:
  home: https://github.com/mantidproject/mantid
  license: GPL-3.0-or-later
  summary: Mantid provides a framework that supports high-performance computing and visualisation of materials science data.

extra:
  recipe-maintainers:
    - StephenSmith25