{% set version = "6.1.1" %}

package:
  name: mantid-qt
  version: {{ version }}

source:
  git_url: https://github.com/mantidproject/mantid.git
  git_tag: 32079_mantidqt_separate_package
  patches:
    # - finder_patch.patch
    # - windows_mantid.patch  # [win]
    #- windows_bundle.patch  # [win]
    #- install_patch.patch

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - ninja  # [unix]
    - cmake
  host:
    - tbb-devel=2020.2.*
    - mantid-framework
    - eigen
    - qscintilla2
    - psutil
    - qt==5.12.9
    - qtpy >=1.5.0
    - setuptools=48.0.0
    - tbb-devel=2020.2.*
    - python.app
    - python

  run:
    - pyqt>=5.12.3,<6
    - qtconsole >=5.0.3,<6
    - matplotlib
    - python
    - python.app

test:
  imports:
    - mantidqt
    - mantidqt.icons

about:
  home: https://github.com/mantidproject/mantid
  license: GPL-3.0-or-later
  summary: Mantid provides a framework that supports high-performance computing and visualisation of materials science data.

extra:
  recipe-maintainers:
    - StephenSmith25