{% set version = "6.1.1" %}

package:
  name: mantid-qt
  version: {{ version }}

source:
  git_url: https://github.com/mantidproject/mantid.git
  git_tag: 32079_mantidqt_separate_package

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('mantid-qt', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - ninja  # [unix]
    - cmake
  host:
    - eigen
    - jemalloc  # [unix]
    - mantid-framework
    - poco
    - python
    - qscintilla2
    - pyqt
    - qt 5.12.*
    - setuptools 48.0.*
    - tbb-devel 2020.2.*

  run:
    - pyqt
    - {{ pin_compatible("qscintilla2", max_pin="x.x") }}
    - qtpy
    - qtconsole
    - matplotlib
    - psutil
    - python

test:
  imports:
    - mantidqt
    - mantidqt.icons

about:
  home: https://github.com/mantidproject/mantid
  license: GPL-3.0-or-later
  summary: Mantid provides a framework that supports high-performance computing and visualisation of materials science data.

extra:
  recipe-maintainers:
    - StephenSmith25